import { defineCustomElement, emit, ensureId, HTMLElementBase } from './internal/dom';

export interface GnomeSwitchRowChangeDetail {
  checked: boolean;
}

export interface GnomeSwitchRowEventMap extends HTMLElementEventMap {
  'gnome-change': CustomEvent<GnomeSwitchRowChangeDetail>;
}

const TITLE_SELECTOR = '[data-slot="row-title"]';
const SUBTITLE_SELECTOR = '[data-slot="row-subtitle"]';
const PREFIX_SELECTOR = '[data-slot="row-prefix"]';
const CONTENT_SELECTOR = '[data-slot="row-content"]';
const SURFACE_SELECTOR = '[data-slot="row-surface"]';
const TRACK_SELECTOR = '[data-slot="row-switch-track"]';

/**
 * Activatable settings row with an integrated switch — mirrors
 * `AdwSwitchRow`.
 *
 * Genuinely different from `gnome-action-row` composed with a nested
 * `gnome-switch`: the entire row is the switch — clicking anywhere toggles
 * it — matching `@gnome-ui/react`'s `SwitchRow`, whose own docs call out
 * that this differs from `ActionRow` + trailing `Switch` because the row
 * itself is the interactive element. Composing a real `<gnome-switch>`
 * (which wraps its own native `<input>`) inside the row's own `<button>`
 * would nest two interactive controls — invalid, inaccessible HTML — so
 * the row's generated `<button data-slot="row-surface">` itself carries
 * `role="switch"`/`aria-checked`, and the switch track/thumb is a small
 * host-generated `aria-hidden` visual: nothing for the consumer to author,
 * same rationale as `gnome-avatar`'s initials.
 *
 * Only `row-title`, `row-subtitle`, and `row-prefix` are consumer-authored
 * (same slot names as `gnome-action-row`); the surface and switch visual
 * are host-generated by default, since — unlike `gnome-action-row` — this
 * row is unconditionally interactive. Author your own
 * `data-slot="row-surface"` (e.g. an `<a>` for a row that navigates) to use
 * a different element; the host adopts it instead of generating one, and
 * falls back to `aria-disabled`/`tabindex="-1"` for `disabled` when the
 * adopted element has no native `disabled` property.
 */
export class GnomeSwitchRowElement extends HTMLElementBase {
  static readonly observedAttributes = ['checked', 'disabled'];

  addEventListener<K extends keyof GnomeSwitchRowEventMap>(
    type: K,
    listener: (this: GnomeSwitchRowElement, event: GnomeSwitchRowEventMap[K]) => void,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject | null,
    options?: boolean | AddEventListenerOptions,
  ): void;
  addEventListener(type: string, listener: unknown, options?: boolean | AddEventListenerOptions) {
    if (listener === null) {
      return;
    }

    super.addEventListener(type, listener as EventListenerOrEventListenerObject, options);
  }

  removeEventListener<K extends keyof GnomeSwitchRowEventMap>(
    type: K,
    listener: (this: GnomeSwitchRowElement, event: GnomeSwitchRowEventMap[K]) => void,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(
    type: string,
    listener: EventListenerOrEventListenerObject | null,
    options?: boolean | EventListenerOptions,
  ): void;
  removeEventListener(type: string, listener: unknown, options?: boolean | EventListenerOptions) {
    if (listener === null) {
      return;
    }

    super.removeEventListener(type, listener as EventListenerOrEventListenerObject, options);
  }

  #connected = false;
  #surface: HTMLElement | null = null;

  #handleSurfaceClick = () => {
    this.checked = !this.checked;
    emit<GnomeSwitchRowChangeDetail>(this, 'gnome-change', { checked: this.checked });
  };

  connectedCallback() {
    this.#connected = true;
    this.#syncContent();
    this.#wrapSurface();
    this.#syncState();
  }

  disconnectedCallback() {
    this.#connected = false;
    this.#detachSurface();
  }

  attributeChangedCallback() {
    if (this.#connected) {
      this.#syncState();
    }
  }

  get checked() {
    return this.hasAttribute('checked');
  }

  set checked(value: boolean) {
    this.toggleAttribute('checked', value);
  }

  get disabled() {
    return this.hasAttribute('disabled');
  }

  set disabled(value: boolean) {
    this.toggleAttribute('disabled', value);
  }

  #syncContent() {
    const existing = this.querySelector<HTMLElement>(CONTENT_SELECTOR);

    if (existing && existing.parentElement === this) {
      return;
    }

    const title = this.querySelector<HTMLElement>(TITLE_SELECTOR);
    const subtitle = this.querySelector<HTMLElement>(SUBTITLE_SELECTOR);

    if (!title && !subtitle) {
      return;
    }

    const content = document.createElement('span');
    content.dataset.slot = 'row-content';

    (title ?? subtitle)?.before(content);

    if (title) {
      content.append(title);
    }

    if (subtitle) {
      content.append(subtitle);
    }
  }

  #wrapSurface() {
    const existing = this.querySelector<HTMLElement>(SURFACE_SELECTOR);

    if (existing && existing.parentElement === this) {
      this.#ensureTrack(existing);
      this.#attachSurface(existing);
      return;
    }

    const surface = document.createElement('button');
    surface.type = 'button';
    surface.dataset.slot = 'row-surface';

    const prefix = this.querySelector<HTMLElement>(PREFIX_SELECTOR);
    const content = this.querySelector<HTMLElement>(CONTENT_SELECTOR);

    (prefix ?? content)?.before(surface);

    if (prefix) {
      surface.append(prefix);
    }

    if (content) {
      surface.append(content);
    }

    this.#ensureTrack(surface);
    this.#attachSurface(surface);
  }

  #ensureTrack(surface: HTMLElement) {
    if (surface.querySelector(TRACK_SELECTOR)) {
      return;
    }

    const track = document.createElement('span');
    track.dataset.slot = 'row-switch-track';
    track.setAttribute('aria-hidden', 'true');

    const thumb = document.createElement('span');
    thumb.dataset.slot = 'row-switch-thumb';
    track.append(thumb);

    surface.append(track);
  }

  #attachSurface(surface: HTMLElement) {
    if (this.#surface === surface) {
      return;
    }

    this.#detachSurface();
    this.#surface = surface;
    surface.addEventListener('click', this.#handleSurfaceClick);
  }

  #detachSurface() {
    this.#surface?.removeEventListener('click', this.#handleSurfaceClick);
    this.#surface = null;
  }

  #syncState() {
    if (!this.#surface) {
      return;
    }

    const content = this.querySelector<HTMLElement>(CONTENT_SELECTOR);

    this.#surface.setAttribute('role', 'switch');
    this.#surface.setAttribute('aria-checked', String(this.checked));

    if (content) {
      this.#surface.setAttribute('aria-labelledby', ensureId(content, 'gnome-switch-row-content'));
    }

    if ('disabled' in this.#surface) {
      const control = this.#surface as HTMLElement & { disabled: boolean };

      if (control.disabled !== this.disabled) {
        control.disabled = this.disabled;
      }
    } else if (this.disabled) {
      this.#surface.setAttribute('aria-disabled', 'true');
      this.#surface.tabIndex = -1;
    } else if (this.#surface.getAttribute('aria-disabled') === 'true') {
      this.#surface.removeAttribute('aria-disabled');
      this.#surface.removeAttribute('tabindex');
    }
  }
}

export function registerGnomeSwitchRow() {
  defineCustomElement('gnome-switch-row', GnomeSwitchRowElement);
}

registerGnomeSwitchRow();

declare global {
  interface HTMLElementTagNameMap {
    'gnome-switch-row': GnomeSwitchRowElement;
  }
}
