import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = join(root, 'public/llms-full.txt');
const checkOnly = process.argv.includes('--check');

const primaryDocs = [
  'README.md',
  'COMPONENT_INDEX.md',
  'GNOME_GUIDELINES.md',
  'ARCHITECTURE.md',
  'packages/core/README.md',
  'packages/icons/README.md',
  'packages/react/README.md',
  'packages/layout/README.md',
  'packages/charts/README.md',
  'packages/platform/README.md',
  'packages/hooks/README.md',
  'packages/cli/README.md',
];

const componentRoots = [
  'packages/react/src/components',
  'packages/layout/src/components',
  'packages/charts/src/components',
];

async function componentDocs(directory) {
  const entries = await readdir(join(root, directory), { withFileTypes: true });
  const docs = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) {
      continue;
    }

    const path = join(directory, entry.name, 'README.md');
    try {
      await readFile(join(root, path), 'utf8');
      docs.push(path);
    } catch (error) {
      if (error?.code !== 'ENOENT') {
        throw error;
      }
    }
  }

  return docs.sort((a, b) => a.localeCompare(b));
}

const componentFiles = (await Promise.all(componentRoots.map(componentDocs))).flat();
const files = [...primaryDocs, ...componentFiles];
const sections = [];

for (const path of files) {
  const markdown = (await readFile(join(root, path), 'utf8')).trim();
  sections.push(`\n---\n\nSource: ${path}\n\n${markdown}`);
}

const generated = `# gnome-ui complete documentation

> Consolidated, LLM-friendly documentation for gnome-ui. Generated from the repository's authoritative Markdown sources; do not edit this file directly.

Use public imports from the documented npm packages. Roadmap items are not released APIs. For a compact index, use https://gnome-ui.org/llms.txt.
${sections.join('\n')}\n`;

if (checkOnly) {
  let current = '';
  try {
    current = await readFile(outputPath, 'utf8');
  } catch (error) {
    if (error?.code !== 'ENOENT') {
      throw error;
    }
  }

  if (current !== generated) {
    console.error(
      `${relative(root, outputPath)} is out of date. Run \`npm run llms:generate\` and commit it.`,
    );
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, generated);
  console.log(`Generated ${relative(root, outputPath)} from ${files.length} Markdown files.`);
}
